[package]
name = "rays-rs"
version = "0.1.0"
authors = ["Julian Goldsmith <julian@juliangoldsmith.com>"]
edition = "2018"

[dependencies]
png = "0.14"
rand = "0.7"
rand_distr = "0.2"
stl = { path = "../rust-stl" }

[dependencies.cgmath]
version = "0.17"
#features = ["simd"]		# Needs unstable.
